---
- hosts: beg_win_clients, mil_win_clients, scada_win_clients, sub_win_clients, wp_scada_win_clients, mil_dmz_win_clients, beg_dmz_win_clients
  remote_user: administrator
  tasks:
    - name: Delete File
      win_file:
        path: C:\Program Files (x86)\Compare It!
        state: absent
      become: yes
      become_method: runas
      become_user: administrator
