---
- hosts: beg_win_clients, mil_win_clients, scada_win_clients, sub_win_clients, wp_scada_win_clients, mil_dmz_win_clients, beg_dmz_win_clients
  tasks:
    - name: Copy SplunkForwarder64bit.msi to system
      win_copy:
        src: SplunkForwarder64bit.msi
        dest: C:\
    - name: Install SUF on Windows Host
      win_shell: msiexec.exe /i C:\SplunkForwarder64bit.msi AGREETOLICENSE=yes DEPLOYMENT_SERVER="10.13.1.60:8089" RECEIVING_INDEXER="10.13.1.60:9997" SPLUNKUSERNAME=splunk SPLUNKPASSWORD=joltgrabdefrostrobin /quiet
    - name: Delete Splunk MSI
      win_file:
        path: C:\SplunkForwarder64bit.msi
        state: absent

